name: learn-github-actions
run-name: Pushing to gitlab Repo
on: push
env: 
  TOKEN: glptt-02c74986f54c55a9e11e51aee25ea1d660cda9d9
  REF_NAME: main
  PROJECT_ID: 44217288
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger gitlab Action 
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: 'https://gitlab.com/api/v4/projects/44217288/trigger/pipeline'
        method: 'POST'
        token: glptt-02c74986f54c55a9e11e51aee25ea1d660cda9d9
        ref: main
        data: '{"token": "glptt-02c74986f54c55a9e11e51aee25ea1d660cda9d9", "ref": "main"}'
      
