name: learn-github-actions
run-name: Pushing to gitlab Repo
on: push
env: 
  TOKEN: glptt-02c74986f54c55a9e11e51aee25ea1d660cda9d9
  REF_NAME: main
  PROJECT_ID: 44217288
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: curl --request POST \ --form token=$TOKEN \ --form ref=$REF_NAME \ "https://gitlab.example.com/api/v4/projects/$PROJECT_ID/trigger/pipeline"
